services:
  ui:
    build:
      context: ./ui
    ports:
      - "60081:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "60031:8000"
    environment:
      PYTHONPATH: /app
    volumes:
      - ./backend/db:/app/db
      - ./backend/backup:/app/backup
      - ./backend/member_cv:/app/member_cv
      - ./backend/products:/app/products
      - ./backend/projects:/app/projects
      - ./backend/resume_images:/app/resume_images
      - ./backend/user:/app/user
    restart: unless-stopped
